name: CI
on: [push, pull_request]

env: 
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${{secrets.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}}
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${{secrets.JWT_RESET_PASSWORD_EXPIRATION_MINUTES}}
  JWT_REFRESH_EXPIRATION_DAYS: ${{secrets.JWT_REFRESH_EXPIRATION_DAYS}}
  JWT_ACCESS_EXPIRATION_MINUTES: ${{secrets.JWT_ACCESS_EXPIRATION_MINUTES}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  PORT: 3000
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test # will run `yarn test` command
